stages:
  - docker-build-test
  - docker-build-master
docker-build-test:
  stage: docker-build-test
  image: docker:latest
  only:
    - developmggoro  
  services: 
    - name: docker:19.03.8-dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE":test .
    - docker push "$CI_REGISTRY_IMAGE":test
    - echo "Registry image:" "$CI_REGISTRY_IMAGE":test
docker-build-master:
  stage: docker-build-master
  image: docker:latest
  only:
    - master  
  services: 
    - name: docker:19.03.8-dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE":latest .
    - docker push "$CI_REGISTRY_IMAGE":latest
    - echo "Registry image:" "$CI_REGISTRY_IMAGE":latest