stages:
    - build
    - test
build:
    stage: build
    script:
      - 'echo "hello, fdffdddgeerwerererwrergsrld!"'
      - 'echo "Start building vvApp"'
      - npm install
      - npm build
      - sudo docker stop gitlabbadquotes
      - sudo  docker rmi gitlabbadquotes
      - sudo docker build --tag gitlabbadquotes:1.0 .
      - sudo  docker run -p 4350:80 -d --name gitlabbadquotescontainer gitlabbadquotes:1.0
      - echo "Build successfully!"
    image: node
test:
    stage: test
    script:
      - 'echo "hello, world!"'
      - 'echo "Testing App"'
      - npm install
      - CI=true
      - 'echo "Test successfully!"'
    image: node 
