stages:
    - build
build:
    stage: build
    script:
      - 'echo "hello, llamando a docker!"'
      - 'echo "Start building vvApp"'
      - npm install
      - npm build
      - echo "Build successfully!"
    image: node