stages:
    - build
    
build:
    stage: build
    script:
      - 'echo "hello, world!"'
      - 'echo "Start building App"'
      - npm install
      - npm build
      - docker stop gitlabbadquotes
      - docker rmi gitlabbadquotes
      - docker build --tag gitlabbadquotes:1.0 .
      - docker run -p 4350:80 -d --name gitlabbadquotescontainer gitlabbadquotes:1.0
      - echo "Build successfully!"
    image: node
test:
    stage: test
    script:
      - 'echo "hello, world!"'
      - 'echo "Testing App"'
      - npm install
      - CI=true
      - 'echo "Test successfully!"'
    image: node 
