stages:
    - deploy
build:
    stage: deploy
    cache:
      paths:
        - node_modules/
    script:
      - 'echo "hello, llamando a docker!"'
      - 'echo "Start building vvApp"'
      - npm install
      - npm build
      - echo "Build successfully!"
    image: node