stages:
    - build
    - test
build:
    stage: build
    script:
      - 'echo "hello, world!"'
      - '  echo "Start building App"'
      - npm install
      - npm build
      - echo "Build successfully!"
    image: node
test:
    stage: test
    script:
      - 'echo "hello, world!"'
      - wecho "Testing App"
      - npm install
      - CI=true
      - npm test
      - echo "Test successfully!"
    image: node
