stages:
  - docker-build
docker-build:
  stage: docker-build
  image: docker:latest
  only:
    - developmggoro  
  services: 
    - name: docker:19.03.8-dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --pull -t pipelina:test .
    - docker push pipelina:test
    - echo "Registry image:" pipelina:test
docker-build:
  stage: docker-build
  image: docker:latest
  only:
    - master  
  services: 
    - name: docker:19.03.8-dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --pull -t pipelina:latest .
    - docker push pipelina:latest
    - echo "Registry image:" pipelina:latest