stages:
    - deploy
build:
    services:
    - docker:dind  
    before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    stage: deploy
    cache:
      paths:
        - node_modules/
    script:
      - 'echo "hello, llamando affff docker!"'
      - 'echo "Start building vvApp"'
      - npm install
      - npm build
      - docker push "$CI_REGISTRY_IMAGE"
      - docker build --pull -t "$CI_REGISTRY_IMAGE" .
      - docker push "$CI_REGISTRY_IMAGE"
    image: node